clone_depth: 5

platform:
  - Win32
  - x64

environment:
  matrix:
  - configuration: Release
  - configuration: Release Lib

# # To allow remote connection to appveyor
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
- ps: >-
      If ($env:Platform -Match "Win32") {
        $env:HDF5_DIR="C:\projects\HDF5-1.8.13-win32"
        If ($env:configuration -Match "Release Lib") {
          Start-FileDownload 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win32-VS2010-static.zip'
          7z x -y hdf5-1.8.13-win32-VS2010-static.zip
        } Else {
          Start-FileDownload 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win32-VS2010-shared.zip'
          7z x -y hdf5-1.8.13-win32-VS2010-shared.zip
        }
        7z x -oC:\projects\HDF5-1.8.13-win32 -y hdf5-1.8.13\HDF5-1.8.13-win32.exe
      } Else {
        $env:HDF5_DIR="C:\projects\HDF5-1.8.13-win64"
        If ($env:configuration -Match "Release Lib") {
          Start-FileDownload 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win64-VS2010-static.zip'
          7z x -y hdf5-1.8.13-win64-VS2010-static.zip
        } Else {
          Start-FileDownload 'https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.13/bin/windows/hdf5-1.8.13-win64-VS2010-shared.zip'
          7z x -y hdf5-1.8.13-win64-VS2010-shared.zip
        }
        7z x -oC:\projects\HDF5-1.8.13-win64 -y hdf5-1.8.13\HDF5-1.8.13-win64.exe
      }
- cmd: "C:\Program Files\Microsoft SDKs\Windows\v7.1\Setup\WindowsSdkVer.exe" -q -version:v7.1
- cmd: call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 /release

build:
  project: visual_studio/matio.sln
  verbosity: normal

after_build:
- cmd: >-
    7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\visual_studio

test: off

artifacts:
  - path: visual_studio\Release\libmatio.lib
    name: libmatio.lib
  - path: visual_studio\Release\libmatio.dll
    name: libmatio.dll
  - path: visual_studio\matio_pubconf.h
    name: matio_pubconf.h
  - path: src\matio.h
    name: matio.h
  - path: myapp.zip
    name: MyApp

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
