language: c

git:
  depth: 5

addons:
  apt:
    packages:
    - hdf5-tools
    - libhdf5-dev
    - hdf5-helpers

matrix:
  include:
    - os: linux
    - os: osx

install:
  # Travis machines have 2 cores
  - JOBS=2
  ############################################################################
  # Install HDF5
  ############################################################################
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        rm -rf /usr/local/include/c++;
        brew install hdf5;
    fi

before_script:
  - ./autogen.sh
  - ./configure --enable-mat73=yes --with-hdf5=/usr/lib/x86_64-linux-gnu/hdf5/serial/

script:
  - make

after_success:
  - make check

notifications:
  email: false

sudo: required



